language: node_js

node_js:
  - 'stable'
  - '4.4'

env:
  global:
    - TWILIO_ACCOUNT_SID=Your-Account-SID
    - TWILIO_AUTH_TOKEN=Your-Twilio-API-KEY
    - TWILIO_API_SECRET=Your-Twilio-API-SECRET
    - TWILIO_IPM_SERVICE_SID=Your-Twilio-IPM-SERVICE-SID

cache:
  directories:
    - node_modules
